# Based on https://github.com/NOAA-ORR-ERD/gridded/blob/master/.travis.yml
# and https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/.travis.yml
language: minimal

sudo: false

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - name: "python3.6"
    - name: "python3.7"
    - name: "python3.8"

env:
  global:
    secure: "UNbdZPiOpDmEdG/S2PVcb0vKj/IwqLIGEPWnUOZ/oXkdjoz6StuZE8iDphuKwLQGhNIee4lkBew/iwSjdQueqxjIQhxA1rvj1kpco5cc445a/ASeAqD1AihCGDXC3EhQ0KJpBEtUOtfiVDlPDy/irVAnWu3DrCw+zExGs15+rUXGZjDU16ZPh+RsLJohdmPjMN/Mk1+c50GIJLMmRu8SFFR6Bh4h/+8yKdqy4lOVc0D+tMAjXBKhPWEF2OpIeLw/s0cVNnCOy30Cyu40vFqzQWDqEeWyteAjmgtIkYOlHTAy2AlF0XNkaNZafEUKf/+laHal597WZc7tfwA8mShAUKG2ZXQRA3GtN6l8TAUc15CF/s7UVSEcaoLvbGXQfHJuIIqweBIdOx/k0Mv1aLX2JgKnJTBPU/Y6wI4Do2gxDR7YH9TTJNCNZkckJPQHOkHKd1qaLtL/ZzvyddZNo2YX8dgfvfEaE/m0OPtNS3/34cSoycqy8EkKe62+z57QyruZmBoi5E/pJrFnS6OvCqEi5Un6JkxyKqCZPNmyie+X9PCELTzPsIM2++PncNuOVXv+pGnZGYB88rNqescPNa8ECaeJpZFVGLIvaELy4CcGvwfV9cemKElCBtpGfwbn0DEJ7o7WQH+xI04P3OV12NLPDyc81XZBSu3jfTYH7dFArNM="

before_install:
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    source $HOME/miniconda/etc/profile.d/conda.sh
    conda activate base
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda install conda-build

install:
  - "./conda_package/travis_ci/install.bash"

script:
  - "./conda_package/travis_ci/test_and_publish_docs.bash"
