{% set name = "mpas_mesh_tools" %}
{% set version = "0.0.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/xylar/MPAS-Tools.git
  git_rev: 4ea5d781e415c15a220ff43f0d064521ba18506a

build:
  number: 0
  entry_points:
    - planar_hex = mpas_mesh_tools.planar_hex:main

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - netcdf4
    - hdf5
    - libnetcdf
  run:
    - netcdf4
    - hdf5
    - libnetcdf
    - numpy
    - xarray

test:
  commands:
    - planar_hex --nx=10 --ny=20 --dc=1000. --outFileName='periodic_mesh_10x10_1km.nc'
    - wget https://github.com/xylar/MPAS-Tools/raw/mesh_tools_conda_package/mesh_tools/mesh_conversion_tools/test/Arctic_Ocean.geojson
    - wget https://github.com/xylar/MPAS-Tools/raw/mesh_tools_conda_package/mesh_tools/mesh_conversion_tools/test/mesh.QU.1920km.151026.nc
    - wget https://github.com/xylar/MPAS-Tools/raw/mesh_tools_conda_package/mesh_tools/mesh_conversion_tools/test/land_mask_final.nc
    - MpasMeshConverter.x mesh.QU.1920km.151026.nc mesh.nc
    - MpasCellCuller.x mesh.nc culled_mesh.nc -m land_mask_final.nc
    - MpasMaskCreator.x mesh.nc arctic_mask.nc -f Arctic_Ocean.geojson

about:
  home: https://github.com/MPAS-Dev/MPAS-Tools/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Mesh tools for Model for Prediction Across Scales (MPAS)
  description: |
    A set of tools for creating and manipulating meshes for the climate
    components based on the Model for Prediction Across Scales (MPAS) framework
  doc_url: 'https://github.com/MPAS-Dev/MPAS-Tools/README.md'
  dev_url: 'https://github.com/MPAS-Dev/MPAS-Tools/'

extra:
  recipe-maintainers:
    - xylar
    - jhkennedy
