name: mpas_tools_docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytest
  - netcdf4
  - hdf5
  - libnetcdf
  - numpy
  - scipy
  - xarray
  - geometric_features
  - pyevtk
  - future
  - backports.tempfile
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
