name: mpas_mesh_tools_docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytest
  - netcdf4
  - hdf5
  - libnetcdf
  - numpy
  - scipy
  - xarray
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
